# Generates a path-and-size manifest from local version 1.3 content.
param(
    [string]$ContentRoot,
    [string]$OutputPath
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repo = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
if (-not $ContentRoot) { $ContentRoot = Join-Path $repo 'game' }
if (-not $OutputPath) { $OutputPath = Join-Path $repo 'src\content_manifest.inc' }

$resource = Join-Path $ContentRoot 'Resource\Common'
if (-not (Test-Path -LiteralPath $resource -PathType Container)) {
    throw "Resource\Common not found under: $ContentRoot"
}

$rootFull = (Resolve-Path -LiteralPath $ContentRoot).Path
$entries = Get-ChildItem -LiteralPath $resource -Recurse -File | ForEach-Object {
    $relative = $_.FullName.Substring($rootFull.Length + 1).Replace('\', '/')
    foreach ($character in $relative.ToCharArray()) {
        if ([int]$character -gt 127) {
            throw "non-ASCII content path: $relative"
        }
    }
    [pscustomobject]@{ Path = $relative; Size = $_.Length }
} | Sort-Object -Property Path

if ($entries.Count -eq 0) {
    throw "no files found under: $resource"
}

$lines = New-Object 'System.Collections.Generic.List[string]'
[void]$lines.Add('// Generated by scripts/gen-content-manifest.ps1 from the supported version 1.3')
[void]$lines.Add('// content. Relative paths and exact byte sizes only; no retail data is stored.')
foreach ($entry in $entries) {
    [void]$lines.Add(('{{ "{0}", {1}ull }},' -f $entry.Path, $entry.Size))
}

Set-Content -LiteralPath $OutputPath -Value $lines -Encoding ascii
Write-Output ("content manifest: {0} entries -> {1}" -f $entries.Count, $OutputPath)
